name = "recoin"
compatibility_date = "2025-04-03"
compatibility_flags = [ "nodejs_compat" ]
main = "./router.server.ts"

[assets]
not_found_handling = "single-page-application"
run_worker_first = [ "/__api", "/__api/*" ]


[[kv_namespaces]]
binding = "RECOIN_WAITING_LIST"
id = "17db23d443574424b365adc2144939b1"

[[d1_databases]]
binding = "DB"
database_name = "recoin-db"
database_id = "2a8921e1-6894-4e17-8ba0-19a38996a1a2"
